# Generated by Django 4.1.3 on 2022-11-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('size', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='images/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=56)),
                ('link_path', models.CharField(max_length=32)),
                ('stack', models.TextField(blank=True)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_index.category')),
                ('images', models.ManyToManyField(blank=True, to='backend_index.projectimage')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, to='backend_index.project'),
        ),
    ]
