# Generated by Django 4.1.3 on 2023-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_index', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_complete',
            field=models.CharField(default='27.01.2023', max_length=28, verbose_name='Дата завершения проекта'),
            preserve_default=False,
        ),
    ]
