# Generated by Django 4.1.3 on 2023-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_index', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=32, verbose_name='Технология')),
                ('color', models.CharField(max_length=12, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(blank=True, null=True, to='backend_index.stack'),
        ),
    ]
