# Generated by Django 4.1.3 on 2023-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_index', '0003_stack_remove_project_stack_project_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание технологии'),
        ),
    ]
