# Generated by Django 4.1.3 on 2023-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_index', '0004_stack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='description',
            field=models.TextField(verbose_name='Описание технологии'),
        ),
    ]
