# Generated by Django 4.1.3 on 2023-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reviews',
            new_name='review',
        ),
    ]
