# Generated by Django 4.1.3 on 2023-01-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category_id',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.PROTECT, to='users.categorynote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
