# Generated by Django 4.1.3 on 2023-01-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryNote',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
