# Generated by Django 4.1.3 on 2022-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requests',
            field=models.ManyToManyField(blank=True, to='users.requestuser', verbose_name='Заявки пользователя'),
        ),
    ]
