# Generated by Django 4.1.3 on 2023-01-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='requests',
        ),
        migrations.AlterField(
            model_name='requestuser',
            name='fk_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
