# Generated by Django 4.1.3 on 2023-01-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_reviews_customuser_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='decoded_password',
            field=models.CharField(default='ba819063', max_length=36),
            preserve_default=False,
        ),
    ]
