# Generated by Django 4.1.3 on 2023-01-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note_category_id_alter_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category_id',
        ),
        migrations.AddField(
            model_name='note',
            name='category_name',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.categorynote'),
        ),
    ]
