# Generated by Django 4.1.3 on 2023-01-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_decoded_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='decoded_password',
        ),
    ]
