# Generated by Django 4.1.3 on 2023-01-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_note_category_id_note_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category_name',
        ),
    ]
