# Generated by Django 4.1.3 on 2023-01-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_decoded_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularreview',
            options={'verbose_name': 'Популярный отзыв', 'verbose_name_plural': 'Популярные отзывы'},
        ),
    ]
