# Generated by Django 4.1.3 on 2023-01-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userreview_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userreview', verbose_name='Отзыв пользователя'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
